Split client and server into separate folders

diff --git a/client/add_sites b/client/add_sites
--- a/client/add_sites
+++ b/client/add_sites
@@ -2,7 +2,7 @@
 
 cd `dirname "$0"`
 this_dir=`pwd`
-cd ../../
+cd ../
 project_dir=`pwd`
 config_file=$project_dir/config
 test -f $config_file || die "No $config_file file found"
@@ -21,5 +21,5 @@ if [ ! "$num_sites" -gt 0 ]; then
   exit 2
 fi
 
-./scripts/remote/upload || die "Failed to upload"
-./scripts/remote/ssh "./scripts/add_sites $num_sites" || die "Failed to add sites"
+./client/upload || die "Failed to upload"
+./client/ssh "./scripts/add_sites $num_sites" || die "Failed to add sites"
