Change terminology site->account

diff --git a/client/add_accounts b/client/add_accounts
--- a/client/add_accounts
+++ b/client/add_accounts
@@ -18,12 +18,12 @@ function die {
 }
 
 if [ ! -z "$1" ]; then
-  num_sites="$1"
+  num_accounts="$1"
 fi
-if [ ! "$num_sites" -gt 0 ]; then
-  echo "Invalid num_sites: $num_sites"
+if [ ! "$num_accounts" -gt 0 ]; then
+  echo "Invalid num_accounts: $num_accounts"
   exit 2
 fi
 
 ./client/upload || die "Failed to upload"
-./client/ssh "./scripts/add_accounts $num_sites" || die "Failed to add sites"
+./client/ssh "./scripts/add_accounts $num_accounts" || die "Failed to add sites"
