Make num_sites a configuration directive

diff --git a/scripts/remote/add_sites b/scripts/remote/add_sites
--- a/scripts/remote/add_sites
+++ b/scripts/remote/add_sites
@@ -1,24 +1,25 @@
 #!/bin/bash
 
+cd `dirname "$0"`
+this_dir=`pwd`
+cd ../../
+project_dir=`pwd`
+config_file=$project_dir/config
+test -f $config_file || die "No $config_file file found"
+eval `cat config`
+
 function die {
   echo "$0" >&2
   exit 1
 }
 
-function usage {
-  echo "Usage: $0 NUM_SITES"
+if [ ! -z "$1" ]; then
+  num_sites="$1"
+fi
+if [ ! "$num_sites" -gt 0 ]; then
+  echo "Invalid num_sites: $num_sites"
   exit 2
-}
-
-if [ -z "$1" ]; then
-  usage
 fi
-if [ "$1" -lt 1 ]; then
-  usage
-fi
-
-cd `dirname "$0"`
-cd ../../
 
 ./scripts/remote/upload || die "Failed to upload"
-./scripts/remote/ssh "./scripts/add_sites $1" || die "Failed to add sites"
+./scripts/remote/ssh "./scripts/add_sites $num_sites" || die "Failed to add sites"
diff --git a/scripts/server/add_sites b/scripts/server/add_sites
--- a/scripts/server/add_sites
+++ b/scripts/server/add_sites
@@ -1,17 +1,22 @@
 #!/bin/bash -e
 
-function usage {
-  echo "Usage: $0 NUM_SITES"
-  exit 2
+function die {
+  echo "$0" >&2
+  exit 1
 }
 
-if [ -z "$1" ]; then
-  usage
+cd
+config_file=./scripts/config
+test -f $config_file || die "No $config_file file found"
+eval `cat $config_file`
+
+if [ ! -z "$1" ]; then
+  num_sites="$1"
 fi
-if [ "$1" -lt 1 ]; then
-  usage
+if [ ! "$num_sites" -gt 0 ]; then
+  echo "Invalid num_sites: $num_sites"
+  exit 2
 fi
-num_users=$1
 
 function read_config {
   cd
@@ -32,7 +37,7 @@ function remove_previous_sites {
 function build_sites_list {
   ( test -f ~/sites && rm ~/sites ) || /bin/true
   n=1
-  while [[ $n -le $num_users ]]; do
+  while [[ $n -le $num_sites ]]; do
     echo "site$n" >> ~/sites
     n=$((n+1))
   done
